services:
  broker:
    container_name: paperless_broker
    image: docker.io/library/redis:8
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - /persist/paperless/redisdata:/data

  db:
    container_name: paperless_db
    image: docker.io/library/postgres:18
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - /persist/paperless/pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  paperless:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    networks:
      - global
      - internal
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "${PORT}:8000"
    volumes:
      - /persist/paperless/data:/usr/src/paperless/data
      - /persist/paperless/media:/usr/src/paperless/media
      - /persist/paperless/export:/usr/src/paperless/export
      - /persist/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    container_name: paperless_gotenberg
    image: docker.io/gotenberg/gotenberg:8.24
    restart: unless-stopped
    networks:
      - internal
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    container_name: paperless_tika
    image: docker.io/apache/tika:latest
    restart: unless-stopped
    networks:
      - internal

volumes:
  data:
  media:
  pgdata:
  redisdata:

networks:
  internal:
    driver: bridge
  global:
    external: true
