services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    user: "1000:1000"
    command: tunnel --no-autoupdate run --token ${TOKEN}
    networks: [global]

networks:
  global:
    external: true

