services:
  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser
    ports:
      - ${PORT}:8080
    networks: [global]
    volumes:
      - /persist/filebrowser:/config
      # shares
      - /data/share:/data
      - /data/downloads:/data/downloads
      - /data/books:/data/books
      - /data/music:/data/music
      - /data/movies:/data/movies
      - /data/shows:/data/shows
      - /data/iso:/data/iso
    environment:
      - FB_BASE_URL=/
    restart: always

networks:
  global:
    external: true
