services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre
    env_file:
      - ports.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      # - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /lab/persist/calibre:/config
      - /lab/data/books:/books
    ports:
      - ${CALIBRE_PORT}:8083
    restart: unless-stopped
    networks:
      - public

networks:
  public:
    external: true
