services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    environment:
      ND_ENABLEINSIGHTSCOLLECTOR: false
    ports:
      - "${PORT}:4533"
    restart: unless-stopped
    volumes:
      - "./data:/data"
      - "/data/music/cache:/data/cache"
      - ${MUSIC_LOCATION}:/music:ro
    networks:
      - public

networks:
  public:
    external: true

