services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code
    hostname: scallop-code
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /persist/code:/config
      - /home/n00dlephr0g/.ssh:/config/.ssh 
    ports:
      - ${PORT}:8443
    restart: unless-stopped
    networks: [global]

networks:
  global:
    external: true
