services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3999:3000'
    user: "1000:1000"
    networks: [global]
    volumes:
      - /persist/grafana:/var/lib/grafana


networks:
  global:
    external: true
